version: "3.9"
services:
  nginx:
    image: nginx:1.19
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      - "80:80"

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: overseer
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  application:
    build: .
    volumes:
      - .:/var/www/html

